language: cpp

compiler:
- clang
- gcc

env:
- QT_BASE=53
- QT_BASE=54

matrix:
  allow_failures:
  - compiler: clang
    env: QT_BASE=53

before_install:
- if [ "$CXX" = "g++" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
- if [ "$QT_BASE" = "53" ]; then sudo add-apt-repository ppa:beineri/opt-qt532 -y; fi
- if [ "$QT_BASE" = "54" ]; then sudo add-apt-repository ppa:beineri/opt-qt541 -y; fi
- sudo apt-get update -qq

install:
- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; export CXX="g++-4.9" CC="gcc-4.9"; fi
- if [ "$QT_BASE" = "53" ]; then sudo apt-get install -qq qt53base qt53script; source /opt/qt53/bin/qt53-env.sh; fi
- if [ "$QT_BASE" = "54" ]; then sudo apt-get install -qq qt54base qt54script; source /opt/qt54/bin/qt54-env.sh; fi

script:
- qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC"
- make check
